# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHwDsdw7w-_KN-0j4GcashYlx-qtbFQl
"""

# algorithm1.py
# Naive Approach: Find Max Product Subarray using Nested Loops

def max_product_naive(arr):
    n = len(arr)
    if n == 0:
        return 0

    max_prod = float('-inf')

    # Loop for start point
    for i in range(n):
        current_prod = 1
        # Loop for end point
        for j in range(i, n):
            current_prod *= arr[j]
            # Update the maximum product found so far
            if current_prod > max_prod:
                max_prod = current_prod

    return max_prod

# Testing
if __name__ == "__main__":
    data = [2.0, 3.0, -2.0, 4.0] # Example growth factors
    print("Naive Max Growth:", max_product_naive(data))

