# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHwDsdw7w-_KN-0j4GcashYlx-qtbFQl
"""

# algorithm2.py
# Optimized Approach: Dynamic Programming (Single Pass)

def max_product_optimized(arr):
    if not arr:
        return 0

    # Initialize variables based on first element
    # We need both max and min because a negative number flips sign
    current_max = arr[0]
    current_min = arr[0]
    final_max = arr[0]

    for i in range(1, len(arr)):
        num = arr[i]

        # We store current_max in temp because it gets updated
        temp_max = max(num, num * current_max, num * current_min)

        # Update current_min
        current_min = min(num, num * current_max, num * current_min)

        # Update current_max using the stored temp
        current_max = temp_max

        # Update the global result
        final_max = max(final_max, current_max)

    return final_max

# Testing
if __name__ == "__main__":
    data = [2.0, 3.0, -2.0, 4.0]
    print("Optimized Max Growth:", max_product_optimized(data))

